// react/src/components/RantList.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import '../styles/rantlist.css';

class RantList extends Component {
    render() {
        return(
            <div className="post-list">
                    
                <Link to="/rant/1">
                    <article className="post">
                        <div className="post__inner">
                            <div className="score">
                                <div className="score__up layout--center">++</div>
                                <div className="score__board layout--center">100</div>
                                <div className="score__down layout--center">--</div>
                                </div>
                            <div className="post__body">
                                    Hello World... </div>
                            </div>
                        <div className="post__footer">
                        <div className="post__time">2m ago</div>
                        <div className="post__comments">
                            <svg className="icon" viewBox="0 0 31 32">
                                    <path d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781 
                                    0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
                                    8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
                                    3.922-2.61 7.23-6.186 8.294z"></path>
                                </svg>
                                23
                            </div>
                        </div>
                    </article>
                </Link>
                    
                <div className="rant__add" title="Add Rant">+</div>        

            </div>
        );
    }
}

export default RantList;

// angular/src/app/rant-list/rant-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { CONSTANTS } from '../../constants';

@Component({
  selector: 'app-rant-list',
  templateUrl: './rant-list.component.html',
  styleUrls: ['./rant-list.component.css']
})
export class RantListComponent implements OnInit {
  isLoading: boolean = false;
  rantList: Array<any> = [];

  constructor(private apiService: ApiService) { }

  ngOnInit() {
    this.getRantList();
  }

  getRantList() {
    this.isLoading = true;
    this.apiService.call('get', {
      url: CONSTANTS.rantList,
      data: {}
    }).then((res) => {
      this.rantList = res['posts'];
      this.isLoading = false;
    }).catch(err=>{
      this.isLoading = false;
    })
  }

}

   <!-- Start of Rant List Page -->
                <!-- ======================= -->

                <div class="post-list">
                    
                        <article class="post">
                              <div class="post__inner">
                                  <div class="score">
                                      <div class="score__up layout--center">++</div>
                                      <div class="score__board layout--center">100</div>
                                      <div class="score__down layout--center">--</div>
                                  </div>
                                  <div class="post__body">
                                      Hello World... </div>
                              </div>
                              <div class="post__footer">
                                  <div class="post__time">2m ago</div>
                                  <div class="post__comments">
                                      <svg class="icon" viewBox="0 0 31 32">
                                          <path d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781 
                                          0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
                                          8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
                                          3.922-2.61 7.23-6.186 8.294z"></path>
                                      </svg>
                                      23
                                  </div>
                              </div>
                          </article>
                          
                          <div class="rant__add" title="Add Rant">+</div>        
      
                      </div>
  
                  <!-- ======================= -->
                  <!-- End of Rant List Page -->
