// react/src/components/App.js
import React, { Component } from 'react';
import Header from './Header'; 
import Loader from './Loader'; 
import RantList from './RantList';
import RantDetails from './RantDetails';
import Login from './Login';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import '../styles/app.css';

class App extends Component {
    render() {
        return (
            <Router>
                <div className="App">
                    <div className="page">

                        <Header />

                        <section className="main layout--center">
                            <div className="main__content layout--wrapped">
                                <Loader isLoading={false} />
                                <Route path="/" exact component={RantList} />
                                <Route path="/rant/:id" component={RantDetails} />
                                <Login isOpen={false}/>
                            </div>
                        </section>

                    </div>
                </div>
            </Router>
        );
    }
}

export default App;

// angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "Eyepax JavaScript Hackathon";
  isLoadingTrue = false;
  isLogingOpen = false;
}

  
    <div class="page">

        <!-- Start of Header -->
		<!-- ======================= -->
  
    
       <app-header></app-header>
		
		<!-- ======================= -->
        <!-- End of Header -->

        <!-- Start of Main Section -->
		<!-- ======================= -->
		
        <section class="main layout--center">
            <div class="main__content layout--wrapped">
               <app-loader *ngIf="isLoadingTrue"></app-loader>
                <!-- ======================= -->
                <!-- End of Rant Details Page-->

                <!-- Start of the routing part -->
                <!-- ======================  -->
                <router-outlet></router-outlet>
                <!-- ======================= -->
                <!-- End of routing part-->

            </div>
        </section>
		
		<!-- ======================= -->
        <!-- End of Main Section -->

    </div>

    <app-login [isOpen]="isLogingOpen"></app-login>
