// angular/src/app/alert/alert.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.css']
})
export class AlertComponent implements OnInit {
  title: string= '';
  description: string= '';

  constructor() { }

  ngOnInit() {
  }

  @Input('title')
  set dataTitle(title: string) {
    this.title = title;
  }

  @Input('description')
  set dataDescription(description: string) {
    this.description = description;
  }

}

 <!-- Start of alert popup -->
    <!-- ======================= -->

    <div class="popup popup--open" [ngClass]="{'popup--open': isOpen}">
        <div class="popup__header">
            <div title="Close" class="close layout--center" (click)="isOpen = !isOpen">
                X
            </div>
        </div>
        <div class="popup__body layout--center">
            <div class="popup__body-inner">

                <div class="form">
                    <div class="form__title">
                        <span class="highlight">#</span>{{title}}
                    </div>
                    <div class="form__description">
                        {{description}}
                    </div>
                    <form name="alert">
                        <div class="alert">
                            <input type="submit" value="OK" (click)="alertClose()"/>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <!-- ======================= -->
    <!-- End of alert popup -->

// react/src/components/Alert.js
import React, { Component } from 'react';

class Alert extends Component {
    constructor(props) {
        super(props);

        this.initialState = {
            isOpenAlert: false
        };

        this.state = this.initialState;
    }

    showHideAlert() {
        const isOpenAlert = this.state.isOpenAlert;
        this.setState({
            isOpenAlert: !isOpenAlert
        });
    }

    render() {
        const title = this.props.title;
        const description = this.props.description;
        const openModal = this.state.isOpenAlert ? 'popup popup--open' : 'popup';

        return (
            <div className={openModal}>
                <div className="popup__header">
                    <div title="Close" className="close layout--center">
                        X
                    </div>
                </div>
                <div className="popup__body layout--center">
                    <div className="popup__body-inner">

                        <div className="form">
                            <div className="form__title">
                                <span className="highlight">#</span>{title}
                            </div>
                            <div className="form__description">
                                {description}
                            </div>
                            <form name="alert">
                                <div className="alert">
                                    <input type="submit" value="OK" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Alert;
