// angular/src/app/login/login.component.ts
import { Component, OnInit, Input } from '@angular/core';
import {NgForm} from '@angular/forms'

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent implements OnInit {
  private isOpen = false;
  private isLoadingTrue = true;
  usernameText: string;
  passwordText: string;
  usernameEmpty: boolean;
  passwordEmpty: boolean;

  constructor() { 
    this.usernameEmpty = false;
    this.passwordEmpty = false;
  }

  ngOnInit() {
    this.usernameText = '';
    this.passwordText = '';
  }

  isOpenChanged() {
    this.isOpen = true;
  }

  onSubmit(f: NgForm) {
    this.validateResults(f);
  }

  validateInputs(f: NgForm) {
      this.validateResults(f);
  }

  validateResults(f) {
    this.usernameEmpty = false;
      this.passwordEmpty = false;
    if (!f.value.username && !f.value.password) {
      this.usernameEmpty = true;
      this.passwordEmpty = true;
    } else if (!f.value.username) {
      this.usernameEmpty = true;
    } else if (!f.value.password) {
      this.passwordEmpty = true;
    }
  }

  @Input('isOpen')
  set data(isOpen: boolean) {
    this.isOpen = isOpen;
  }

}

  <!-- Start of login popup -->
    <!-- ======================= -->

    <div [ngClass]="{'popup': true, 'popup--open': isOpen}">
        <div class="popup__header">
            <div title="Close" class="close layout--center"  (click)="isOpen = !isOpen">
                X
            </div>
        </div>
        <div class="popup__body layout--center">
            <div class="popup__body-inner">

                <div class="form">
                    <div class="form__title">
                        JOIN <span class="highlight">#</span>DEVRANT
                    </div>
                    <div class="form__description">
                        Vote and comment on others' rants. Post your own.
                    </div>
                    <form name="login" #f="ngForm" (ngSubmit)="onSubmit(f)" novalidate>
                        <div class="login">
                            <input type="text" name="username" placeholder="USERNAME" #username ngModel (blur)="validateInputs(f)" />
                            
                            <input type="password" name="password" placeholder="PASSWORD" ngModel #password (blur)="validateInputs(f)"/>
                            
                            <div class="loader">
                                <app-loader *ngIf="isLoadingTrue"></app-loader>
                            </div>
                            <div class="form__error">
                                <div *ngIf="usernameEmpty">Username is required</div>
                                <div *ngIf="passwordEmpty">Password is required</div>
                            </div>

                            <input type="submit" value="LET ME IN" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- ======================= -->
    <!-- End of login popup -->

// react/src/components/Login.js
import React, { Component } from 'react';
import '../styles/login.css';

class Login extends Component {
    constructor(props) {
        super(props);

        this.handleLoginModal = this.handleLoginModal.bind(this);
    }

    handleLoginModal() {
        this.props.handleLoginModal();
    }

    render() {
        let isOpen = this.props.isOpen;
        let popupClass = isOpen ? 'popup popup--open' : 'popup';

        return(
            <div className={popupClass}>
                <div className="popup__header">
                    <div title="Close" className="close layout--center" onClick={this.handleLoginModal}>
                        X
                    </div>
                </div>
                <div className="popup__body layout--center">
                    <div className="popup__body-inner">

                        <div className="form">
                            <div className="form__title">
                                JOIN <span className="highlight">#</span>DEVRANT
                            </div>
                            <div className="form__description">
                                Vote and comment on others' rants. Post your own.
                            </div>
                            <form className="login">
                                <div className="login">

                                    <input type="text" placeholder="USERNAME" />
                                    <input type="password" placeholder="PASSWORD" />

                                    <div className="loader">
                                        <div className="spinner"></div>
                                    </div>

                                    <div className="form__error">
                                        Some fields are missing !
                                    </div>

                                    <input type="submit" value="LET ME IN" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Login;
