// angular/src/app/rant/rant.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-rant',
  templateUrl: './rant.component.html',
  styleUrls: ['./rant.component.css']
})
export class RantComponent implements OnInit {
  rantValues:any = [];
  upVoted:boolean = false;
  downVoted:boolean = false;

  @Input('rantValues')
  set data(rantValues: boolean) {
    this.rantValues = rantValues;
    if(this.rantValues['myVote'] == 1) {
      this.upVoted['myVote'] = true;
    } else if (this.rantValues['myVote'] == -1){
      this.downVoted['myVote'] = true;
    }
  }


  constructor() { }

  ngOnInit() {

  }

}


<article class="post">
    <div class="post__inner">
        <div class="score">
            <div class="score__up layout--center" [ngClass]="{ 'checked' : upVoted}">++</div>
            <div class="score__board layout--center">{{rantValues.votes}}</div>
            <div class="score__down layout--center" [ngClass]="{'checked' : downVoted}">--</div>
        </div>
        <div class="post__body">
            {{rantValues.content}} </div>
    </div>
    <div class="post__footer">
        <div class="post__time">{{rantValues.displayTime}}</div>
        <div class="post__comments">
            <svg class="icon" viewBox="0 0 31 32">
                <path d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781 
                0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
                8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
                3.922-2.61 7.23-6.186 8.294z"></path>
            </svg>
            {{rantValues.commentCount}}
        </div>
    </div>
</article>

// react/src/components/Rant.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import '../styles/rant.css';

class Rant extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        const post = this.props.post;
        const myUpvote = (post.myVote > 0) ? 'checked' : '';
        const myDownvote = (post.myVote < 0) ? 'checked' : '';
        
        return (
            <article className="post">
                <Link to={"/rant/" + post.id}>
                    <div className="post__inner">
                        <div className="score"> 
                            <div className={"score__up layout--center " + myUpvote}>++</div>
                            <div className="score__board layout--center">{post.votes}</div>
                            <div className={"score__down layout--center " + myDownvote}>--</div>
                            </div>
                        <div className="post__body">{post.content}</div>
                        </div>
                    <div className="post__footer">
                        <div className="post__time">{post.displayTime}</div>
                    <div className="post__comments">
                        <svg className="icon" viewBox="0 0 31 32">
                                <path d="M24.732 24.371v7.629l-7.267-7.267h-8.808c-4.781 
                                0-8.657-3.875-8.657-8.657v-7.42c0-4.781 3.876-8.657 
                                8.657-8.657h13.604c4.781 0 8.657 3.875 8.657 8.657v7.42c0 
                                3.922-2.61 7.23-6.186 8.294z"></path>
                            </svg>
                            {post.commentCount}
                        </div>
                    </div>
                </Link>
            </article>        
        );
    }
}

export default Rant;
