// react/src/components/Header.js
import React, {Component} from 'react';
import '../styles/header.css';

class Header extends Component {
    constructor(props) {
        super(props);

        this.openLoginModal = this.openLoginModal.bind(this);
    }

    openLoginModal() {
        this.props.openLoginModal();
    }

    render() {
        return (
            <section className="header layout--center">
                <div className="header__content layout--wrapped">
                    <div className="brand">
                        <a href="/"><div className="brand__name"><span>#</span>DEVRANT</div></a>
                    </div>

                    {/* <div className="profile layout--center">
                        <div className="profile__picture">
                            <svg height="36" width="36">
                                <circle cx="18" cy="18" r="18" fill="#5c5f6f"></circle>
                            </svg>
                        </div>
                        <div className="profile__name">Elon</div>
                    </div> */}

                    <div className="join">
                        <span onClick={this.openLoginModal}>Join</span>
                        {/* <span>Sign Out</span> */}
                    </div>
                </div>
            </section>
        );
    }
}

export default Header;

// angular/src/app/header/header.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  @Output() joinEvent = new EventEmitter<boolean>();

  constructor() { }

  ngOnInit() {
  }

  openLoginModal() {
    this.joinEvent.emit(true);
  }

}

<section class="header layout--center">
    <div class="header__content layout--wrapped">
        <div class="brand">
            <a href="/"><div class="brand__name"><span>#</span>DEVRANT</div></a>
        </div>

        <!-- User Profile -->
        <!-- <div class="profile layout--center">
            <div class="profile__picture">
                <svg height="36" width="36">
                    <circle cx="18" cy="18" r="18" fill="#5c5f6f"></circle>
                </svg>
            </div>
            <div class="profile__name">Elon</div>
        </div> -->

        <div class="join">
            <span (click)="openLoginModal()">Join</span>
            <!-- <span>Sign Out</span> -->
        </div>
    </div>
</section>
<app-login *ngIf="isOpen"></app-login>
